# Generated by Django 3.0.7 on 2020-07-15 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bill_split_app', '0002_auto_20200712_1152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='money_borrowed',
        ),
        migrations.AddField(
            model_name='member',
            name='expenditure_on_self',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='member',
            name='expenditure_on_others',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='member',
            name='expenditure_on_team',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Expenditure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payee', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=20)),
                ('money_borrowed', models.IntegerField(default=0)),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bill_split_app.Member')),
            ],
        ),
    ]
