# Generated by Django 3.0.7 on 2020-07-15 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill_split_app', '0003_auto_20200715_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenditure',
            name='payee',
            field=models.CharField(max_length=20),
        ),
    ]
