# Generated by Django 3.0.7 on 2020-07-15 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill_split_app', '0005_auto_20200715_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='amount_borrowed',
            field=models.IntegerField(default=0),
        ),
    ]
