# Generated by Django 3.0.7 on 2020-07-15 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bill_split_app', '0006_member_amount_borrowed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='expenditure_on_team',
        ),
    ]
