# Generated by Django 3.0.7 on 2020-07-17 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill_split_app', '0007_remove_member_expenditure_on_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='net_payment',
            field=models.IntegerField(default=0),
        ),
    ]
